### ISSUE TITLE
Incorrect default Idris2-lsp path on windows

### ISSUE THREAD

**Issue by elseLuna** [bamboo/idris2-lsp-vscode#11]
On windows, if Idris 2 and the LSP have been installed via MSYS2, (i.e. not running through wsl) `Idris2-lsp: Path` needs to be changed from `idris2-lsp` to `idris2-lsp.cmd` (assuming `path\to\.idris2\bin` is in `PATH` of course)

Is it possible to have different default settings per platform?

If not, then at least the README should be updated to tell windows users it needs to be changed.

**Comment by lsby** [comment]
This pull request should also resolve this issue: https://github.com/bamboo/idris2-lsp-vscode/pull/12

**Comment by elseLuna** [comment]
Yes, I can confirm it's fixed.
