### ISSUE TITLE
`Go To Definition` for `import` statements

### ISSUE THREAD

**Issue by scarf005** [bamboo/idris2-lsp-vscode#17]
https://github.com/bamboo/idris2-lsp-vscode/assets/54838975/55295956-7374-47e5-9da3-f573e43b92df

currently we can go to definition via individual declarations (function), however it doesn't work for import statements. It'd be great if the same could be done for imports.

**Comment by srghma** [comment]
yes, purescript has it

that should be implemented in https://github.com/idris-community/idris2-lsp/
