### ISSUE TITLE
Please Publish Version 0.7.1 to VSCode Marketplace

### ISSUE THREAD

**Issue by lsby** [bamboo/idris2-lsp-vscode#19]
Hello,

The latest version of the idris2-lsp VSCode plugin available in the [VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=bamboo.idris2-lsp) is 0.7.0. However, due to recent updates in VSCode, which include updates to the Node.js version, the security patch now prohibits the use of the spawn command without the shell option on Windows (see the [Node.js April 2024 Security Releases](https://nodejs.org/en/blog/vulnerability/april-2024-security-releases-2) for details).

This change causes the 0.7.0 version of the plugin to no longer function on Windows systems.

Interestingly, there was a [pull request #12](https://github.com/bamboo/idris2-lsp-vscode/pull/12/files) which was originally intended to address other issues, but it also added the shell option to the spawn command. This inadvertently fixed the compatibility issue with the latest Node.js security update. I noticed that after merging this PR, the version was updated to 0.7.1, but this version has not been published to the VSCode Marketplace.

I have tested the 0.7.1 version (the latest code) by compiling and installing it in my environment, and it works correctly.

Could you please publish the 0.7.1 version to the VSCode Marketplace so that users can continue to use the plugin without issues on Windows?

**Comment by bamboo** [comment]
Hi @lsby, thanks for the heads-up. I'm currently away from home but I should be able to publish a new version on Sunday.

**Comment by bamboo** [comment]
Version 0.7.1 of the extension has been published. Please let me know if it works for you so this issue can be closed.

**Comment by lsby** [comment]
Hi @bamboo 
Thank you for publishing version 0.7.1. I have tested it, and it works correctly on my Windows system. The issue is now resolved.

**Comment by bamboo** [comment]
Thanks for checking 👍
