### ISSUE TITLE
[Feature request] Add support for the new `repl` LSP command.

### ISSUE THREAD

**Issue by Russoul** [bamboo/idris2-lsp-vscode#4]
The LSP command was implemented here: https://github.com/idris-community/idris2-lsp/pull/89

**Comment by bamboo** [comment]
Thanks for the suggestion. This is now implemented:

<img width="805" alt="Screen Shot 2021-09-15 at 18 57 31" src="https://user-images.githubusercontent.com/51689/133515485-fd341154-409f-4bd4-9444-02dceb68598c.png">


A preview of the result is displayed inline and the full result is displayed in a hover window.
